---

name: CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: lambda-feedback-segp-sandbox/test-response-area-action@v1
  publish:
    name: Publish
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        uses: lambda-feedback-segp-sandbox/publish-response-area-action@v1
