---

name: CI

on: push

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: lambda-feedback-segp-sandbox/test-response-area-action@v1
  publish:
    name: Publish
    if: github.ref == 'refs/heads/main'
    needs: test
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.pages-url }}
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        id: publish
        uses: lambda-feedback-segp-sandbox/publish-response-area-action@v1
